name: Django run

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reactDjangoV1/requirements.txt
          pip install pytest pytest-django

      - name: Set up SQLite database
        run: |
          # Créer la base de données SQLite
          touch reactDjangoV1/db.sqlite3

      - name: Run migrations
        run: |
          python reactDjangoV1/manage.py migrate

      - name: Run tests with pytest
        run: |
          pytest reactDjangoV1/back/tests.py
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install React dependencies
        run: |
          cd reactDjangoV1/frontend
          npm install

      - name: Run React tests with Jest
        run: |
          cd reactDjangoV1/frontend
          npm test -- --watchAll=false --coverage